# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0002_auto_20180204_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=125)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.BigIntegerField(unique=True)),
                ('sexo', models.CharField(default='M', max_length=1)),
            ],
        ),
    ]
