# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0003_passageiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corridas.Motorista')),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corridas.Passageiro')),
            ],
        ),
    ]
